# Generated by Django 4.2.17 on 2024-12-30 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                (
                    "board_affiliation",
                    models.CharField(
                        choices=[
                            ("CBSE", "Central Board of Secondary Education"),
                            ("ICSE", "Indian Certificate of Secondary Education"),
                            ("STATE", "State Board"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "student_strength",
                    models.PositiveIntegerField(
                        help_text="Maximum 500 students allowed in free tier",
                        validators=[django.core.validators.MaxValueValidator(500)],
                    ),
                ),
                (
                    "staff_count",
                    models.PositiveIntegerField(
                        help_text="Maximum 50 staff members allowed in free tier",
                        validators=[django.core.validators.MaxValueValidator(50)],
                    ),
                ),
                ("principal_name", models.CharField(max_length=100)),
                ("principal_email", models.EmailField(max_length=254)),
                ("principal_phone", models.CharField(max_length=20)),
                ("is_approved", models.BooleanField(default=False)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "academic_year_start",
                    models.IntegerField(
                        choices=[(4, "April"), (6, "June")],
                        default=4,
                        help_text="Month when academic year starts",
                    ),
                ),
                (
                    "academic_year_end",
                    models.IntegerField(
                        choices=[(3, "March"), (5, "May")],
                        default=3,
                        help_text="Month when academic year ends",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="core.school",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
